// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace eTravelAgencija.Services.Migrations
{
    [DbContext(typeof(eTravelAgencijaDbContext))]
    [Migration("20251118013040_mainFixingDatabase")]
    partial class mainFixingDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 11, 18, 1, 30, 39, 834, DateTimeKind.Utc).AddTicks(5021),
                            Description = "",
                            IsActive = true
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3,
                            CreatedAt = new DateTime(2025, 11, 18, 1, 30, 39, 834, DateTimeKind.Utc).AddTicks(5028),
                            Description = "",
                            IsActive = true
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 11, 18, 1, 30, 39, 834, DateTimeKind.Utc).AddTicks(5029),
                            Description = "",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("offerId")
                        .HasColumnType("integer");

                    b.Property<int>("starRate")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("offerId");

                    b.HasIndex("userId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CalculatedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Address = "Via Roma 12",
                            CalculatedPrice = 0m,
                            Name = "Hotel Medici",
                            Stars = 4
                        },
                        new
                        {
                            Id = 101,
                            Address = "Piazza Duomo 2",
                            CalculatedPrice = 0m,
                            Name = "Hotel Firenze Centro",
                            Stars = 3
                        },
                        new
                        {
                            Id = 102,
                            Address = "Ponte Vecchio 5",
                            CalculatedPrice = 0m,
                            Name = "Hotel Ponte Vecchio",
                            Stars = 5
                        },
                        new
                        {
                            Id = 110,
                            Address = "Santorini Beach 9",
                            CalculatedPrice = 0m,
                            Name = "Blue Dome Resort",
                            Stars = 5
                        },
                        new
                        {
                            Id = 111,
                            Address = "Oia Street 44",
                            CalculatedPrice = 0m,
                            Name = "Aegean View",
                            Stars = 4
                        },
                        new
                        {
                            Id = 112,
                            Address = "Fira 21",
                            CalculatedPrice = 0m,
                            Name = "White Cave Hotel",
                            Stars = 3
                        },
                        new
                        {
                            Id = 120,
                            Address = "Sultanahmet 1",
                            CalculatedPrice = 0m,
                            Name = "Hotel Sultanahmet",
                            Stars = 4
                        },
                        new
                        {
                            Id = 121,
                            Address = "Galata 5",
                            CalculatedPrice = 0m,
                            Name = "Galata Inn",
                            Stars = 3
                        },
                        new
                        {
                            Id = 122,
                            Address = "Bosfor Blvd 7",
                            CalculatedPrice = 0m,
                            Name = "Bosfor Palace Hotel",
                            Stars = 5
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.HotelImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("HotelImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelId = 100,
                            ImageUrl = "hotel100_main.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 2,
                            HotelId = 100,
                            ImageUrl = "hotel100_1.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 3,
                            HotelId = 100,
                            ImageUrl = "hotel100_2.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 4,
                            HotelId = 100,
                            ImageUrl = "hotel100_3.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 5,
                            HotelId = 101,
                            ImageUrl = "hotel101_main.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 6,
                            HotelId = 101,
                            ImageUrl = "hotel101_1.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 7,
                            HotelId = 101,
                            ImageUrl = "hotel101_2.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 8,
                            HotelId = 101,
                            ImageUrl = "hotel101_3.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 9,
                            HotelId = 102,
                            ImageUrl = "hotel102_main.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 10,
                            HotelId = 102,
                            ImageUrl = "hotel102_1.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 11,
                            HotelId = 102,
                            ImageUrl = "hotel102_2.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 12,
                            HotelId = 102,
                            ImageUrl = "hotel102_3.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 13,
                            HotelId = 110,
                            ImageUrl = "hotel110_main.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 14,
                            HotelId = 110,
                            ImageUrl = "hotel110_1.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 15,
                            HotelId = 110,
                            ImageUrl = "hotel110_2.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 16,
                            HotelId = 110,
                            ImageUrl = "hotel110_3.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 17,
                            HotelId = 111,
                            ImageUrl = "hotel111_main.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 18,
                            HotelId = 111,
                            ImageUrl = "hotel111_1.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 19,
                            HotelId = 111,
                            ImageUrl = "hotel111_2.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 20,
                            HotelId = 111,
                            ImageUrl = "hotel111_3.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 21,
                            HotelId = 112,
                            ImageUrl = "hotel112_main.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 22,
                            HotelId = 112,
                            ImageUrl = "hotel112_1.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 23,
                            HotelId = 112,
                            ImageUrl = "hotel112_2.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 24,
                            HotelId = 112,
                            ImageUrl = "hotel112_3.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 25,
                            HotelId = 120,
                            ImageUrl = "hotel120_main.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 26,
                            HotelId = 120,
                            ImageUrl = "hotel120_1.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 27,
                            HotelId = 120,
                            ImageUrl = "hotel120_2.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 28,
                            HotelId = 120,
                            ImageUrl = "hotel120_3.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 29,
                            HotelId = 121,
                            ImageUrl = "hotel121_main.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 30,
                            HotelId = 121,
                            ImageUrl = "hotel121_1.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 31,
                            HotelId = 121,
                            ImageUrl = "hotel121_2.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 32,
                            HotelId = 121,
                            ImageUrl = "hotel121_3.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 33,
                            HotelId = 122,
                            ImageUrl = "hotel122_main.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 34,
                            HotelId = 122,
                            ImageUrl = "hotel122_1.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 35,
                            HotelId = 122,
                            ImageUrl = "hotel122_2.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 36,
                            HotelId = 122,
                            ImageUrl = "hotel122_3.jpg",
                            IsMain = false
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.HotelRooms", b =>
                {
                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomsLeft")
                        .HasColumnType("integer");

                    b.HasKey("HotelId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("HotelRooms");

                    b.HasData(
                        new
                        {
                            HotelId = 100,
                            RoomId = 1,
                            RoomsLeft = 10
                        },
                        new
                        {
                            HotelId = 100,
                            RoomId = 2,
                            RoomsLeft = 6
                        },
                        new
                        {
                            HotelId = 100,
                            RoomId = 3,
                            RoomsLeft = 4
                        },
                        new
                        {
                            HotelId = 100,
                            RoomId = 4,
                            RoomsLeft = 8
                        },
                        new
                        {
                            HotelId = 101,
                            RoomId = 1,
                            RoomsLeft = 10
                        },
                        new
                        {
                            HotelId = 101,
                            RoomId = 2,
                            RoomsLeft = 6
                        },
                        new
                        {
                            HotelId = 101,
                            RoomId = 3,
                            RoomsLeft = 4
                        },
                        new
                        {
                            HotelId = 101,
                            RoomId = 4,
                            RoomsLeft = 8
                        },
                        new
                        {
                            HotelId = 102,
                            RoomId = 1,
                            RoomsLeft = 10
                        },
                        new
                        {
                            HotelId = 102,
                            RoomId = 2,
                            RoomsLeft = 6
                        },
                        new
                        {
                            HotelId = 102,
                            RoomId = 3,
                            RoomsLeft = 4
                        },
                        new
                        {
                            HotelId = 102,
                            RoomId = 4,
                            RoomsLeft = 8
                        },
                        new
                        {
                            HotelId = 110,
                            RoomId = 1,
                            RoomsLeft = 10
                        },
                        new
                        {
                            HotelId = 110,
                            RoomId = 2,
                            RoomsLeft = 6
                        },
                        new
                        {
                            HotelId = 110,
                            RoomId = 3,
                            RoomsLeft = 4
                        },
                        new
                        {
                            HotelId = 110,
                            RoomId = 4,
                            RoomsLeft = 8
                        },
                        new
                        {
                            HotelId = 111,
                            RoomId = 1,
                            RoomsLeft = 10
                        },
                        new
                        {
                            HotelId = 111,
                            RoomId = 2,
                            RoomsLeft = 6
                        },
                        new
                        {
                            HotelId = 111,
                            RoomId = 3,
                            RoomsLeft = 4
                        },
                        new
                        {
                            HotelId = 111,
                            RoomId = 4,
                            RoomsLeft = 8
                        },
                        new
                        {
                            HotelId = 112,
                            RoomId = 1,
                            RoomsLeft = 10
                        },
                        new
                        {
                            HotelId = 112,
                            RoomId = 2,
                            RoomsLeft = 6
                        },
                        new
                        {
                            HotelId = 112,
                            RoomId = 3,
                            RoomsLeft = 4
                        },
                        new
                        {
                            HotelId = 112,
                            RoomId = 4,
                            RoomsLeft = 8
                        },
                        new
                        {
                            HotelId = 120,
                            RoomId = 1,
                            RoomsLeft = 10
                        },
                        new
                        {
                            HotelId = 120,
                            RoomId = 2,
                            RoomsLeft = 6
                        },
                        new
                        {
                            HotelId = 120,
                            RoomId = 3,
                            RoomsLeft = 4
                        },
                        new
                        {
                            HotelId = 120,
                            RoomId = 4,
                            RoomsLeft = 8
                        },
                        new
                        {
                            HotelId = 121,
                            RoomId = 1,
                            RoomsLeft = 10
                        },
                        new
                        {
                            HotelId = 121,
                            RoomId = 2,
                            RoomsLeft = 6
                        },
                        new
                        {
                            HotelId = 121,
                            RoomId = 3,
                            RoomsLeft = 4
                        },
                        new
                        {
                            HotelId = 121,
                            RoomId = 4,
                            RoomsLeft = 8
                        },
                        new
                        {
                            HotelId = 122,
                            RoomId = 1,
                            RoomsLeft = 10
                        },
                        new
                        {
                            HotelId = 122,
                            RoomId = 2,
                            RoomsLeft = 6
                        },
                        new
                        {
                            HotelId = 122,
                            RoomId = 3,
                            RoomsLeft = 4
                        },
                        new
                        {
                            HotelId = 122,
                            RoomId = 4,
                            RoomsLeft = 8
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysInTotal")
                        .HasColumnType("integer");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WayOfTravel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaysInTotal = 5,
                            SubCategoryId = 1,
                            Title = "Firenca",
                            WayOfTravel = "Autobus"
                        },
                        new
                        {
                            Id = 2,
                            DaysInTotal = 7,
                            SubCategoryId = 1,
                            Title = "Santorini",
                            WayOfTravel = "Avion"
                        },
                        new
                        {
                            Id = 3,
                            DaysInTotal = 4,
                            SubCategoryId = 1,
                            Title = "Istanbul",
                            WayOfTravel = "Autobus"
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OfferCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Praznična putovanja"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Specijalna putovanja"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Osjetite mjesec"
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferDetails", b =>
                {
                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MinimalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ResidenceTaxPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ResidenceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TravelInsuranceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OfferId");

                    b.ToTable("OfferDetails");

                    b.HasData(
                        new
                        {
                            OfferId = 1,
                            City = "Firenca",
                            Country = "Italija",
                            Description = "Putovanje u prekrasnu Firencu.",
                            MinimalPrice = 450m,
                            ResidenceTaxPerDay = 2.00m,
                            ResidenceTotal = 10m,
                            TravelInsuranceTotal = 15m
                        },
                        new
                        {
                            OfferId = 2,
                            City = "Santorini",
                            Country = "Grčka",
                            Description = "Santorini – raj na zemlji.",
                            MinimalPrice = 900m,
                            ResidenceTaxPerDay = 3.00m,
                            ResidenceTotal = 21m,
                            TravelInsuranceTotal = 25m
                        },
                        new
                        {
                            OfferId = 3,
                            City = "Istanbul",
                            Country = "Turska",
                            Description = "Istanbul – čarolija dva kontinenta.",
                            MinimalPrice = 350m,
                            ResidenceTaxPerDay = 1.50m,
                            ResidenceTotal = 6m,
                            TravelInsuranceTotal = 12m
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferHotels", b =>
                {
                    b.Property<int>("OfferDetailsId")
                        .HasColumnType("integer");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OfferDetailsId", "HotelId");

                    b.HasIndex("HotelId");

                    b.ToTable("OfferHotels");

                    b.HasData(
                        new
                        {
                            OfferDetailsId = 1,
                            HotelId = 100,
                            DepartureDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReturnDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferDetailsId = 1,
                            HotelId = 101,
                            DepartureDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReturnDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferDetailsId = 1,
                            HotelId = 102,
                            DepartureDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReturnDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferDetailsId = 2,
                            HotelId = 110,
                            DepartureDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReturnDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferDetailsId = 2,
                            HotelId = 111,
                            DepartureDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReturnDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferDetailsId = 2,
                            HotelId = 112,
                            DepartureDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReturnDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferDetailsId = 3,
                            HotelId = 120,
                            DepartureDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReturnDate = new DateTime(2025, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferDetailsId = 3,
                            HotelId = 121,
                            DepartureDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReturnDate = new DateTime(2025, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferDetailsId = 3,
                            HotelId = 122,
                            DepartureDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReturnDate = new DateTime(2025, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<bool>("isMain")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("OfferImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "firenca_main.jpg",
                            OfferId = 1,
                            isMain = true
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "firenca_1.jpg",
                            OfferId = 1,
                            isMain = false
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "firenca_2.jpg",
                            OfferId = 1,
                            isMain = false
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "firenca_3.jpg",
                            OfferId = 1,
                            isMain = false
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "santorini_main.jpg",
                            OfferId = 2,
                            isMain = true
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "santorini_1.jpg",
                            OfferId = 2,
                            isMain = false
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "santorini_2.jpg",
                            OfferId = 2,
                            isMain = false
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "santorini_3.jpg",
                            OfferId = 2,
                            isMain = false
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "istanbul_main.jpg",
                            OfferId = 3,
                            isMain = true
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "istanbul_1.jpg",
                            OfferId = 3,
                            isMain = false
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "istanbul_2.jpg",
                            OfferId = 3,
                            isMain = false
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "istanbul_3.jpg",
                            OfferId = 3,
                            isMain = false
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferPlanDay", b =>
                {
                    b.Property<int>("OfferDetailsId")
                        .HasColumnType("integer");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<string>("DayDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DayTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OfferDetailsId", "DayNumber");

                    b.ToTable("OfferPlanDays");

                    b.HasData(
                        new
                        {
                            OfferDetailsId = 1,
                            DayNumber = 1,
                            DayDescription = "Polazak u ranim jutarnjim satima. Pauze tokom puta. Dolazak u Firencu u poslijepodnevnim satima. Smještaj u hotel i slobodno vrijeme za odmor ili šetnju centrom grada.",
                            DayTitle = "Polazak i dolazak u Firencu"
                        },
                        new
                        {
                            OfferDetailsId = 1,
                            DayNumber = 2,
                            DayDescription = "Doručak. Organizovano razgledanje: Katedrala Santa Maria del Fiore, Piazza della Signoria, Palazzo Vecchio i Ponte Vecchio. Popodne slobodno vrijeme za individualno istraživanje i kupovinu suvenira.",
                            DayTitle = "Upoznavanje sa starim gradom"
                        },
                        new
                        {
                            OfferDetailsId = 1,
                            DayNumber = 3,
                            DayDescription = "Posjeta čuvenoj galeriji Uffizi – remek-djela renesansnih umjetnika: Botticelli, Michelangelo, Da Vinci. Nakon obilaska, slobodno vrijeme za ručak u lokalnim restoranima i uživanje u talijanskoj kuhinji.",
                            DayTitle = "Galerija Uffizi i slobodno popodne"
                        },
                        new
                        {
                            OfferDetailsId = 1,
                            DayNumber = 4,
                            DayDescription = "Mogućnost fakultativnog izleta u Pisu i posjete Krivom tornju. Alternativno, slobodan dan u Firenci za šoping, obilazak muzeja, degustaciju vina ili šetnju slikovitim ulicama.",
                            DayTitle = "Izlet u Pisu ili slobodan dan"
                        },
                        new
                        {
                            OfferDetailsId = 1,
                            DayNumber = 5,
                            DayDescription = "Check-out iz hotela i polazak prema kući. Pauze tokom puta. Dolazak u kasnim večernjim satima.",
                            DayTitle = "Povratak kući"
                        },
                        new
                        {
                            OfferDetailsId = 2,
                            DayNumber = 1,
                            DayDescription = "Let ili transfer do Santorinija. Smještaj u hotel. Slobodno vrijeme za odmor, kupanje ili večernju šetnju rivom u Firi.",
                            DayTitle = "Dolazak na Santorini"
                        },
                        new
                        {
                            OfferDetailsId = 2,
                            DayNumber = 2,
                            DayDescription = "Nakon doručka slijedi obilazak Fire: uske bijele ulice, crkve sa plavim kupolama i prekrasni vidikovci. Popodne slobodno vrijeme za kupovinu ili posjetu lokalnim tavernama.",
                            DayTitle = "Fira – glavni grad ostrva"
                        },
                        new
                        {
                            OfferDetailsId = 2,
                            DayNumber = 3,
                            DayDescription = "Prijepodnevno slobodno vrijeme za plažu. U poslijepodnevnim satima odlazak u Oiu – najpoznatije mjesto na Santoriniju. Uživanje u fantastičnom zalasku sunca.",
                            DayTitle = "Oia – najljepši zalazak sunca"
                        },
                        new
                        {
                            OfferDetailsId = 2,
                            DayNumber = 4,
                            DayDescription = "Obilazak vulkanskih plaža: Red Beach i Perissa (Black Beach). Slobodno vrijeme za kupanje i sunčanje. Povratak u hotel u večernjim satima.",
                            DayTitle = "Crna i crvena plaža"
                        },
                        new
                        {
                            OfferDetailsId = 2,
                            DayNumber = 5,
                            DayDescription = "Izlet brodom do vulkanskog ostrva Nea Kameni, šetnja kraterom i kupanje u toplim termalnim izvorima. Povratak brodom u luku.",
                            DayTitle = "Vulkansko ostrvo i termalni izvori"
                        },
                        new
                        {
                            OfferDetailsId = 2,
                            DayNumber = 6,
                            DayDescription = "Dan predviđen za odmor, kupanje ili fakultativne aktivnosti – iznajmljivanje quada, degustacije vina, panoramska vožnja ostrvom.",
                            DayTitle = "Slobodan dan"
                        },
                        new
                        {
                            OfferDetailsId = 2,
                            DayNumber = 7,
                            DayDescription = "Odjava iz hotela i povratak kući prema planu putovanja.",
                            DayTitle = "Povratak kući"
                        },
                        new
                        {
                            OfferDetailsId = 3,
                            DayNumber = 1,
                            DayDescription = "Dolazak u Istanbul i smještaj u hotel. Slobodno vrijeme za odmor. Uveče mogućnost odlaska na večeru u tradicionalni turski restoran.",
                            DayTitle = "Dolazak u Istanbul"
                        },
                        new
                        {
                            OfferDetailsId = 3,
                            DayNumber = 2,
                            DayDescription = "Obilazak najvećih atrakcija: Aja Sofija, Sultanahmet džamija, Hipodrom i Topkapi palata. Popodne slobodno vrijeme ili posjeta Grand Bazaru.",
                            DayTitle = "Stari dio Istanbula – Sultanahmet"
                        },
                        new
                        {
                            OfferDetailsId = 3,
                            DayNumber = 3,
                            DayDescription = "Jutarnje krstarenje Bosforom – pogled na palače, mostove i obalu. U popodnevnim satima odlazak na Taksim trg i šetnja Istiklal ulicom.",
                            DayTitle = "Bosfor krstarenje i Taksim"
                        },
                        new
                        {
                            OfferDetailsId = 3,
                            DayNumber = 4,
                            DayDescription = "Slobodno vrijeme do polaska. Odjava iz hotela i povratak kući.",
                            DayTitle = "Povratak kući"
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("OfferSubCategories");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CategoryId = 2,
                            Name = "Bez podkategorije"
                        },
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Božić"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Bajram"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Prvi maj"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Name = "Januar"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Februar"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Mart"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "April"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Maj"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Juni"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Juli"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Name = "August"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Septembar"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "Oktobar"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Name = "Novembar"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Decembar"
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Payment", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int>("RateId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("DeadlineExtended")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PaymentDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReservationId", "RateId");

                    b.HasIndex("RateId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Prva rata",
                            OrderNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Druga rata",
                            OrderNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Treća rata",
                            OrderNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Puni iznos",
                            OrderNumber = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Preostali iznos",
                            OrderNumber = 0
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<bool>("IncludeInsurance")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceLeftToPay")
                        .HasColumnType("numeric");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("addedNeeds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isFirstRatePaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("isFullPaid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("OfferId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Osnovna korisnička rola",
                            Name = "Korisnik",
                            NormalizedName = "KORISNIK"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Zaposleni koji upravlja ponudama i rezervacijama",
                            Name = "Radnik",
                            NormalizedName = "RADNIK"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Administrator sistema",
                            Name = "Direktor",
                            NormalizedName = "DIREKTOR"
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Rooms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomCount")
                        .HasColumnType("integer");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomCount = 2,
                            RoomType = "Dvokrevetna"
                        },
                        new
                        {
                            Id = 2,
                            RoomCount = 3,
                            RoomType = "Trokrevetna"
                        },
                        new
                        {
                            Id = 3,
                            RoomCount = 2,
                            RoomType = "Petokrevetna"
                        },
                        new
                        {
                            Id = 4,
                            RoomCount = 4,
                            RoomType = "Cetverokrevetna"
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MainImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("isBlocked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8cb56a4d-09f0-4f3c-8587-684ef3ebef2b",
                            CreatedAt = new DateTime(2025, 11, 18, 1, 30, 39, 641, DateTimeKind.Utc).AddTicks(1106),
                            DateBirth = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "radnik@etravel.com",
                            EmailConfirmed = true,
                            FirstName = "Marko",
                            LastName = "Radnik",
                            LockoutEnabled = false,
                            MainImage = "test",
                            NormalizedEmail = "RADNIK@ETRAVEL.COM",
                            NormalizedUserName = "RADNIK",
                            PasswordHash = "AQAAAAIAAYagAAAAECqqkxxPoPRE44nL9SE/4piJ5UccVd0TxHJ+31WSysZqJ8dhEBCKH39sk3fKFX8rxQ==",
                            PhoneNumber = "+38761111111",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "radnik",
                            isBlocked = false
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "76033641-7f74-4bb5-a246-900ca7de2f40",
                            CreatedAt = new DateTime(2025, 11, 18, 1, 30, 39, 709, DateTimeKind.Utc).AddTicks(9330),
                            DateBirth = new DateTime(1985, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "direktor@etravel.com",
                            EmailConfirmed = true,
                            FirstName = "Amir",
                            LastName = "Direktor",
                            LockoutEnabled = false,
                            MainImage = "test",
                            NormalizedEmail = "DIREKTOR@ETRAVEL.COM",
                            NormalizedUserName = "DIREKTOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEMRKBPKoF3OR7JUmGosiBQXrAwfsoIdc99U4xZap2j+3lItsJNaLjgwr++xX+VP3DA==",
                            PhoneNumber = "+38762222222",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "direktor",
                            isBlocked = false
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0a4b8abf-39e9-447c-b279-0a06696cebcc",
                            CreatedAt = new DateTime(2025, 11, 18, 1, 30, 39, 777, DateTimeKind.Utc).AddTicks(2078),
                            DateBirth = new DateTime(2002, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "korisnik@etravel.com",
                            EmailConfirmed = true,
                            FirstName = "Ajdin",
                            LastName = "Korisnik",
                            LockoutEnabled = false,
                            MainImage = "test",
                            NormalizedEmail = "KORISNIK@ETRAVEL.COM",
                            NormalizedUserName = "KORISNIK",
                            PasswordHash = "AQAAAAIAAYagAAAAEKoX7ISEN0eRVo2kTZmNR3wrq0aXPgV1l39NdFhw8qECSNMfcHK3DuJNE/GWAkgnEQ==",
                            PhoneNumber = "+38763333333",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "korisnik",
                            isBlocked = false
                        });
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Equity")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.UserVoucher", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VoucherId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "VoucherId");

                    b.HasIndex("VoucherId");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("priceInTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.WorkApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CvFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkApplications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.Role", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eTravelAgencija.Services.Database.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Comment", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.Offer", "offer")
                        .WithMany()
                        .HasForeignKey("offerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eTravelAgencija.Services.Database.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("offer");

                    b.Navigation("user");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.HotelImages", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.Hotel", "Hotel")
                        .WithMany("HotelImages")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.HotelRooms", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.Hotel", "Hotel")
                        .WithMany("HotelRooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eTravelAgencija.Services.Database.Rooms", "Rooms")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Offer", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.OfferSubCategory", "SubCategory")
                        .WithMany("Offers")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferDetails", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.Offer", "Offer")
                        .WithOne("Details")
                        .HasForeignKey("eTravelAgencija.Services.Database.OfferDetails", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferHotels", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.Hotel", "Hotel")
                        .WithMany("OfferHotels")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eTravelAgencija.Services.Database.OfferDetails", "OfferDetails")
                        .WithMany("OfferHotels")
                        .HasForeignKey("OfferDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("OfferDetails");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferImage", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.OfferDetails", "OfferDetails")
                        .WithMany("OfferImages")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferDetails");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferPlanDay", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.OfferDetails", "OfferDetails")
                        .WithMany("OfferPlanDays")
                        .HasForeignKey("OfferDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferDetails");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferSubCategory", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.OfferCategory", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Payment", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.Rate", "Rate")
                        .WithMany()
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eTravelAgencija.Services.Database.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rate");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Reservation", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eTravelAgencija.Services.Database.OfferDetails", "OfferDetails")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eTravelAgencija.Services.Database.Rooms", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eTravelAgencija.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("OfferDetails");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.UserToken", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.UserVoucher", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.User", "User")
                        .WithMany("UserVouchers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eTravelAgencija.Services.Database.Voucher", "Voucher")
                        .WithMany("UserVouchers")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.WorkApplication", b =>
                {
                    b.HasOne("eTravelAgencija.Services.Database.User", "User")
                        .WithMany("workApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Hotel", b =>
                {
                    b.Navigation("HotelImages");

                    b.Navigation("HotelRooms");

                    b.Navigation("OfferHotels");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Offer", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferDetails", b =>
                {
                    b.Navigation("OfferHotels");

                    b.Navigation("OfferImages");

                    b.Navigation("OfferPlanDays");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.OfferSubCategory", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Reservation", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.User", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("UserVouchers");

                    b.Navigation("workApplications");
                });

            modelBuilder.Entity("eTravelAgencija.Services.Database.Voucher", b =>
                {
                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
