
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app


EXPOSE 5265
ENV ASPNETCORE_URLS=http://+:5265


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .


RUN dotnet restore eTravelAgencija.sln


RUN dotnet publish eTravelAgencija.WebAPI/eTravelAgencija.WebAPI.csproj \
    -c Release \
    -o /app/publish

FROM base AS final
WORKDIR /app

# Kopiraj build
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "eTravelAgencija.WebAPI.dll"]
