# --------------------
# BUILD STAGE
# --------------------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Kopiraj csproj i restore
COPY eTravelAgencija.EmailConsumer/eTravelAgencija.EmailConsumer.csproj eTravelAgencija.EmailConsumer/
RUN dotnet restore eTravelAgencija.EmailConsumer/eTravelAgencija.EmailConsumer.csproj

# Kopiraj sve i build
COPY . .
WORKDIR /src/eTravelAgencija.EmailConsumer
RUN dotnet publish -c Release -o /app/publish

# --------------------
# RUNTIME STAGE
# --------------------
FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "eTravelAgencija.EmailConsumer.dll"]
